// Generated by gencpp from file jackal_2dnav/sInstance.msg
// DO NOT EDIT!


#ifndef JACKAL_2DNAV_MESSAGE_SINSTANCE_H
#define JACKAL_2DNAV_MESSAGE_SINSTANCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace jackal_2dnav
{
template <class ContainerAllocator>
struct sInstance_
{
  typedef sInstance_<ContainerAllocator> Type;

  sInstance_()
    : objPose()
    , objLabel()  {
    }
  sInstance_(const ContainerAllocator& _alloc)
    : objPose(_alloc)
    , objLabel(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _objPose_type;
  _objPose_type objPose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _objLabel_type;
  _objLabel_type objLabel;





  typedef boost::shared_ptr< ::jackal_2dnav::sInstance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jackal_2dnav::sInstance_<ContainerAllocator> const> ConstPtr;

}; // struct sInstance_

typedef ::jackal_2dnav::sInstance_<std::allocator<void> > sInstance;

typedef boost::shared_ptr< ::jackal_2dnav::sInstance > sInstancePtr;
typedef boost::shared_ptr< ::jackal_2dnav::sInstance const> sInstanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::jackal_2dnav::sInstance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::jackal_2dnav::sInstance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::jackal_2dnav::sInstance_<ContainerAllocator1> & lhs, const ::jackal_2dnav::sInstance_<ContainerAllocator2> & rhs)
{
  return lhs.objPose == rhs.objPose &&
    lhs.objLabel == rhs.objLabel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::jackal_2dnav::sInstance_<ContainerAllocator1> & lhs, const ::jackal_2dnav::sInstance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace jackal_2dnav

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::jackal_2dnav::sInstance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::jackal_2dnav::sInstance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jackal_2dnav::sInstance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::jackal_2dnav::sInstance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_2dnav::sInstance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::jackal_2dnav::sInstance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::jackal_2dnav::sInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e34956c628ce888a52ead1e1e7269e9";
  }

  static const char* value(const ::jackal_2dnav::sInstance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e34956c628ce888ULL;
  static const uint64_t static_value2 = 0xa52ead1e1e7269e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::jackal_2dnav::sInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "jackal_2dnav/sInstance";
  }

  static const char* value(const ::jackal_2dnav::sInstance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::jackal_2dnav::sInstance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose objPose\n"
"string objLabel\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::jackal_2dnav::sInstance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::jackal_2dnav::sInstance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objPose);
      stream.next(m.objLabel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sInstance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jackal_2dnav::sInstance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::jackal_2dnav::sInstance_<ContainerAllocator>& v)
  {
    s << indent << "objPose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.objPose);
    s << indent << "objLabel: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.objLabel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JACKAL_2DNAV_MESSAGE_SINSTANCE_H
