# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jackal_2dnav/grasslands.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import jackal_2dnav.msg

class grasslands(genpy.Message):
  _md5sum = "46f47fc035cf3ac098d5a2252afa7df8"
  _type = "jackal_2dnav/grasslands"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """jackal_2dnav/grassLimits[] grasslands

================================================================================
MSG: jackal_2dnav/grassLimits
float64 minX
float64 maxX

float64 minY
float64 maxY
"""
  __slots__ = ['grasslands']
  _slot_types = ['jackal_2dnav/grassLimits[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       grasslands

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(grasslands, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.grasslands is None:
        self.grasslands = []
    else:
      self.grasslands = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.grasslands)
      buff.write(_struct_I.pack(length))
      for val1 in self.grasslands:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.minX, _x.maxX, _x.minY, _x.maxY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grasslands is None:
        self.grasslands = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grasslands = []
      for i in range(0, length):
        val1 = jackal_2dnav.msg.grassLimits()
        _x = val1
        start = end
        end += 32
        (_x.minX, _x.maxX, _x.minY, _x.maxY,) = _get_struct_4d().unpack(str[start:end])
        self.grasslands.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.grasslands)
      buff.write(_struct_I.pack(length))
      for val1 in self.grasslands:
        _x = val1
        buff.write(_get_struct_4d().pack(_x.minX, _x.maxX, _x.minY, _x.maxY))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.grasslands is None:
        self.grasslands = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.grasslands = []
      for i in range(0, length):
        val1 = jackal_2dnav.msg.grassLimits()
        _x = val1
        start = end
        end += 32
        (_x.minX, _x.maxX, _x.minY, _x.maxY,) = _get_struct_4d().unpack(str[start:end])
        self.grasslands.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
